=== vilinian/Mobius_AionEmu/dist/game/data/static_data/instance_bonusattr/instance_bonusattr.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.1">
	<xs:include schemaLocation="../modifiers.xsd" />
	<xs:element name="instance_bonusattrs">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="instance_bonusattr" type="InstanceBonusAttr" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="InstanceBonusAttr">
		<xs:sequence>
			<xs:element name="penalty_attr" type="InstancePenaltyAttr" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="buff_id" type="xs:int" use="required" />
	</xs:complexType>
	<xs:complexType name="InstancePenaltyAttr">
		<xs:attribute name="stat" type="modifiersenum" use="required" />
		<xs:attribute name="func" type="StatFunc" use="required" />
		<xs:attribute name="value" type="xs:int" use="required" />
	</xs:complexType>
</xs:schema>

=== vilinian/Mobius_AionEmu/dist/game/data/static_data/instance_bonusattr/instance_bonusattr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- parsed by phpTools from Aion Germany Group (Mariella) at 2021-01-18 20:07 -->
<instance_bonusattrs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="instance_bonusattr.xsd">
	<instance_bonusattr buff_id="1">
		<penalty_attr stat="PHYSICAL_ACCURACY" func="ADD" value="1100" />
		<penalty_attr stat="MAGICAL_ACCURACY" func="ADD" value="800" />
		<penalty_attr stat="PVP_ATTACK_RATIO" func="ADD" value="500" />
		<penalty_attr stat="PVP_DEFEND_RATIO" func="ADD" value="350" />
		<penalty_attr stat="SPEED" func="PERCENT" value="70" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="2">
		<penalty_attr stat="PHYSICAL_ATTACK" func="ADD" value="15" />
		<penalty_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="95" />
		<penalty_attr stat="MAXHP" func="ADD" value="440" />
		<penalty_attr stat="HEAL_SKILL_BOOST" func="ADD" value="30" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="3">
		<penalty_attr stat="PHYSICAL_ATTACK" func="ADD" value="20" />
		<penalty_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="105" />
		<penalty_attr stat="MAXHP" func="ADD" value="520" />
		<penalty_attr stat="HEAL_SKILL_BOOST" func="ADD" value="30" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="4">
		<penalty_attr stat="PHYSICAL_ATTACK" func="ADD" value="20" />
		<penalty_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="115" />
		<penalty_attr stat="MAXHP" func="ADD" value="600" />
		<penalty_attr stat="HEAL_SKILL_BOOST" func="ADD" value="30" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="5">
		<penalty_attr stat="PHYSICAL_ATTACK" func="ADD" value="25" />
		<penalty_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="125" />
		<penalty_attr stat="MAXHP" func="ADD" value="680" />
		<penalty_attr stat="HEAL_SKILL_BOOST" func="ADD" value="50" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="6">
		<penalty_attr stat="PHYSICAL_ATTACK" func="ADD" value="25" />
		<penalty_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="125" />
		<penalty_attr stat="MAXHP" func="ADD" value="680" />
		<penalty_attr stat="HEAL_SKILL_BOOST" func="ADD" value="50" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="7">
		<penalty_attr stat="PHYSICAL_DEFENSE" func="ADD" value="99999" />
		<penalty_attr stat="MAGICAL_DEFEND" func="ADD" value="99999" />
		<penalty_attr stat="EVASION" func="ADD" value="99999" />
		<penalty_attr stat="MAGICAL_RESIST" func="ADD" value="99999" />
		<penalty_attr stat="ABNORMAL_RESISTANCE_ALL" func="ADD" value="9999" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="8">
		<penalty_attr stat="PHYSICAL_DEFENSE" func="ADD" value="9999" />
		<penalty_attr stat="MAGICAL_DEFEND" func="ADD" value="9999" />
		<penalty_attr stat="EVASION" func="ADD" value="99999" />
		<penalty_attr stat="MAGICAL_RESIST" func="ADD" value="99999" />
		<penalty_attr stat="ABNORMAL_RESISTANCE_ALL" func="ADD" value="9999" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="9">
		<penalty_attr stat="PVP_ATTACK" func="ADD" value="400" />
		<penalty_attr stat="PVP_DEFENSE" func="ADD" value="400" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="10">
		<penalty_attr stat="PVP_DEFEND_RATIO" func="ADD" value="1000" />
		<penalty_attr stat="SPEED" func="PERCENT" value="50" />
		<penalty_attr stat="MAGICAL_RESIST" func="ADD" value="9999" />
		<penalty_attr stat="ABNORMAL_RESISTANCE_ALL" func="ADD" value="1000" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="11">
		<penalty_attr stat="PVP_DEFEND_RATIO" func="ADD" value="1000" />
		<penalty_attr stat="SPEED" func="PERCENT" value="50" />
		<penalty_attr stat="MAGICAL_RESIST" func="ADD" value="9999" />
		<penalty_attr stat="ABNORMAL_RESISTANCE_ALL" func="ADD" value="1000" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="12">
		<penalty_attr stat="PVP_DEFEND_RATIO" func="ADD" value="1000" />
		<penalty_attr stat="SPEED" func="PERCENT" value="50" />
		<penalty_attr stat="MAGICAL_RESIST" func="ADD" value="9999" />
		<penalty_attr stat="ABNORMAL_RESISTANCE_ALL" func="ADD" value="1000" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="13">
		<penalty_attr stat="FEAR_RESISTANCE" func="ADD" value="200" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="14">
		<penalty_attr stat="PHYSICAL_ATTACK" func="ADD" value="25" />
		<penalty_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="125" />
		<penalty_attr stat="MAXHP" func="ADD" value="1000" />
		<penalty_attr stat="HEAL_SKILL_BOOST" func="ADD" value="50" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="15">
		<penalty_attr stat="PVP_ATTACK" func="ADD" value="400" />
		<penalty_attr stat="PVP_DEFENSE" func="ADD" value="400" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="16">
		<penalty_attr stat="PVP_DEFENSE" func="ADD" value="400" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="17">
		<penalty_attr stat="MAXHP" func="ADD" value="30000" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="18">
		<penalty_attr stat="MAXHP" func="ADD" value="5000" />
	</instance_bonusattr>
	<instance_bonusattr buff_id="19">
		<penalty_attr stat="PHYSICAL_ATTACK" func="ADD" value="25" />
		<penalty_attr stat="BOOST_MAGICAL_SKILL" func="ADD" value="125" />
		<penalty_attr stat="MAXHP" func="ADD" value="2000" />
	</instance_bonusattr>
</instance_bonusattrs>
