=== vilinian/Mobius_AionEmu/dist/game/data/static_data/player_initial_data.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="items/item/item_templates.xsd" />
	<xs:include schemaLocation="global_types.xsd" />
	<xs:element name="player_initial_data">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="asmodian_spawn_location" type="spawnLocationType" minOccurs="1" maxOccurs="1" />
				<xs:element name="elyos_spawn_location" type="spawnLocationType" minOccurs="1" maxOccurs="1" />
				<xs:element name="player_data" type="playerDataType" minOccurs="1" maxOccurs="8" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="playerDataType">
		<xs:sequence>
			<xs:element name="items" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="id" type="itemId" use="required" />
								<xs:attribute name="count" type="xs:int" use="required" />
								<xs:attribute name="race" type="Race" use="required" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="class" type="startingPlayerClass" />
	</xs:complexType>
	<xs:complexType name="spawnLocationType">
		<!-- TODO: remove map_id -->
		<xs:attribute name="map_id" type="xs:int" use="required" />
		<xs:attribute name="x" type="xs:float" use="required" />
		<xs:attribute name="y" type="xs:float" use="required" />
		<xs:attribute name="z" type="xs:float" use="required" />
		<xs:attribute name="heading" type="xs:byte" use="required" />
	</xs:complexType>
</xs:schema>

=== vilinian/Mobius_AionEmu/dist/game/data/static_data/player_initial_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<player_initial_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="player_initial_data.xsd">
	<asmodian_spawn_location map_id="220010000" heading="80" x="595.3203" y="2465.4019" z="279.65676" /> <!-- 6.x -->
	<elyos_spawn_location map_id="210010000" heading="45" x="873.781" y="1185.4426" z="110.3707" /> <!-- 6.x -->
	<player_data class="WARRIOR">
		<items>
			<item id="182400001" count="0" race="PC_ALL" /> <!-- Kinah 6.x -->
			<item id="100050065" count="1" race="ASMODIANS" /> <!-- Old Longsword 6.x -->
			<item id="115050124" count="1" race="ASMODIANS" /> <!-- Old Battle Shield 6.x -->
			<item id="110650062" count="1" race="ASMODIANS" /> <!-- Old Breastplate 6.x -->
			<item id="113650062" count="1" race="ASMODIANS" /> <!-- Old Plate Greaves 6.x -->
			<item id="111650062" count="1" race="ASMODIANS" /> <!-- Old Plate Gauntlets 6.x -->
			<item id="114650062" count="1" race="ASMODIANS" /> <!-- Old Sabatons 6.x -->
			<item id="100050064" count="1" race="ELYOS" /> <!-- Old Longsword 6.x -->
			<item id="115050122" count="1" race="ELYOS" /> <!-- Old Battle Shield 6.x -->
			<item id="110650061" count="1" race="ELYOS" /> <!-- Old Breastplate 6.x -->
			<item id="113650061" count="1" race="ELYOS" /> <!-- Old Plate Greaves 6.x -->
			<item id="111650061" count="1" race="ELYOS" /> <!-- Old Plate Gauntlets 6.x -->
			<item id="114650061" count="1" race="ELYOS" /> <!-- Old Sabatons 6.x -->
			<item id="160020008" count="10" race="PC_ALL" /> <!-- Malodor Juice 6.x -->
			<item id="169300002" count="20" race="PC_ALL" /> <!-- Bandage 6.x -->
			<item id="162005039" count="50" race="PC_ALL" /> <!-- Apprentices Recovery Potion 6.x -->
			<item id="162005040" count="50" race="PC_ALL" /> <!-- Apprentices Recovery Serum 6.x -->
		</items>
	</player_data>
	<player_data class="MAGE">
		<items>
			<item id="182400001" count="0" race="PC_ALL" /> <!-- Kinah 6.x -->
			<item id="100650065" count="1" race="ASMODIANS" /> <!-- Old Spellbook 6.x -->
			<item id="110150062" count="1" race="ASMODIANS" /> <!-- Old Tunic 6.x -->
			<item id="113150062" count="1" race="ASMODIANS" /> <!-- Old Cloth Breeches 6.x -->
			<item id="111150062" count="1" race="ASMODIANS" /> <!-- Old Cloth Gloves 6.x -->
			<item id="114150062" count="1" race="ASMODIANS" /> <!-- Old Cloth Shoes 6.x -->
			<item id="100650064" count="1" race="ELYOS" /> <!-- Old Spellbook 6.x -->
			<item id="110150061" count="1" race="ELYOS" /> <!-- Old Tunic 6.x -->
			<item id="113150061" count="1" race="ELYOS" /> <!-- Old Cloth Breeches 6.x -->
			<item id="111150061" count="1" race="ELYOS" /> <!-- Old Cloth Gloves 6.x -->
			<item id="114150061" count="1" race="ELYOS" /> <!-- Old Cloth Shoes 6.x -->
			<item id="160020008" count="10" race="PC_ALL" /> <!-- Malodor Juice 6.x -->
			<item id="169300002" count="20" race="PC_ALL" /> <!-- Bandage 6.x -->
			<item id="162005039" count="50" race="PC_ALL" /> <!-- Apprentices Recovery Potion 6.x -->
			<item id="162005040" count="50" race="PC_ALL" /> <!-- Apprentices Recovery Serum 6.x -->
		</items>
	</player_data>
	<player_data class="PRIEST">
		<items>
			<item id="182400001" count="0" race="PC_ALL" /> <!-- Kinah 6.x -->
			<item id="100150065" count="1" race="ASMODIANS" /> <!-- Old Mace 6.x -->
			<item id="110550124" count="1" race="ASMODIANS" /> <!-- Old Chain Cuirass 6.x -->
			<item id="113550124" count="1" race="ASMODIANS" /> <!-- Old Chausses 6.x -->
			<item id="111550124" count="1" race="ASMODIANS" /> <!-- Old Chain Gauntlets 6.x -->
			<item id="114550124" count="1" race="ASMODIANS" /> <!-- Old Brogans 6.x -->
			<item id="100150064" count="1" race="ELYOS" /> <!-- Old Mace 6.x -->
			<item id="110550122" count="1" race="ELYOS" /> <!-- Old Chain Cuirass 6.x -->
			<item id="113550122" count="1" race="ELYOS" /> <!-- Old Chausses 6.x -->
			<item id="111550122" count="1" race="ELYOS" /> <!-- Old Chain Gauntlets 6.x -->
			<item id="114550122" count="1" race="ELYOS" /> <!-- Old Brogans 6.x -->
			<item id="160020008" count="10" race="PC_ALL" /> <!-- Malodor Juice 6.x -->
			<item id="169300002" count="20" race="PC_ALL" /> <!-- Bandage 6.x -->
			<item id="162005039" count="50" race="PC_ALL" /> <!-- Apprentices Recovery Potion 6.x -->
			<item id="162005040" count="50" race="PC_ALL" /> <!-- Apprentices Recovery Serum 6.x -->
		</items>
	</player_data>
	<player_data class="SCOUT">
		<items>
			<item id="182400001" count="0" race="PC_ALL" /> <!-- Kinah 6.x -->
			<item id="100250065" count="1" race="ASMODIANS" /> <!-- Old Dagger 6.x -->
			<item id="110350124" count="1" race="ASMODIANS" /> <!-- Old Leather Doublet 6.x -->
			<item id="113350124" count="1" race="ASMODIANS" /> <!-- Old Leather Legwear 6.x -->
			<item id="111350124" count="1" race="ASMODIANS" /> <!-- Old Vambraces 6.x -->
			<item id="114350124" count="1" race="ASMODIANS" /> <!-- Old Leather Shoes 6.x -->
			<item id="100250064" count="1" race="ELYOS" /> <!-- Old Dagger 6.x -->
			<item id="110350122" count="1" race="ELYOS" /> <!-- Old Leather Doublet 6.x -->
			<item id="113350122" count="1" race="ELYOS" /> <!-- Old Leather Legwear 6.x -->
			<item id="111350122" count="1" race="ELYOS" /> <!-- Old Vambraces 6.x -->
			<item id="114350122" count="1" race="ELYOS" /> <!-- Old Leather Shoes 6.x -->
			<item id="160020008" count="10" race="PC_ALL" /> <!-- Malodor Juice 6.x -->
			<item id="169300002" count="20" race="PC_ALL" /> <!-- Bandage 6.x -->
			<item id="162005039" count="50" race="PC_ALL" /> <!-- Apprentices Recovery Potion 6.x -->
			<item id="162005040" count="50" race="PC_ALL" /> <!-- Apprentices Recovery Serum 6.x -->
		</items>
	</player_data>
	<player_data class="ENGINEER">
		<items>
			<item id="182400001" count="0" race="PC_ALL" /> <!-- Kinah 6.x -->
			<item id="101850065" count="1" race="ASMODIANS" /> <!-- Old Aether Revolver 6.x -->
			<item id="110350125" count="1" race="ASMODIANS" /> <!-- Old Jerkin 6.x -->
			<item id="113350125" count="1" race="ASMODIANS" /> <!-- Old Breeches 6.x -->
			<item id="111350125" count="1" race="ASMODIANS" /> <!-- Old Leather Gauntlets 6.x -->
			<item id="114350125" count="1" race="ASMODIANS" /> <!-- Old Leather Footwear 6.x -->
			<item id="101850064" count="1" race="ELYOS" /> <!-- Old Aether Revolver 6.x -->
			<item id="110350123" count="1" race="ELYOS" /> <!-- Old Jerkin 6.x -->
			<item id="113350123" count="1" race="ELYOS" /> <!-- Old Breeches 6.x -->
			<item id="111350123" count="1" race="ELYOS" /> <!-- Old Leather Gauntlets 6.x -->
			<item id="114350123" count="1" race="ELYOS" /> <!-- Old Leather Footwear 6.x -->
			<item id="160020008" count="10" race="PC_ALL" /> <!-- Malodor Juice 6.x -->
			<item id="169300002" count="20" race="PC_ALL" /> <!-- Bandage 6.x -->
			<item id="162005039" count="50" race="PC_ALL" /> <!-- Apprentices Recovery Potion 6.x -->
			<item id="162005040" count="50" race="PC_ALL" /> <!-- Apprentices Recovery Serum 6.x -->
		</items>
	</player_data>
	<player_data class="ARTIST">
		<items>
			<item id="182400001" count="0" race="PC_ALL" /> <!-- Kinah 6.x -->
			<item id="102050065" count="1" race="ASMODIANS" /> <!-- Old Stringed Instrument 6.x -->
			<item id="102220103" count="1" race="ASMODIANS" /> <!-- Old Paint Rings 7.x -->
			<item id="110150062" count="1" race="ASMODIANS" /> <!-- Old Tunic 6.x -->
			<item id="113150062" count="1" race="ASMODIANS" /> <!-- Old Cloth Breeches 6.x -->
			<item id="111150062" count="1" race="ASMODIANS" /> <!-- Old Cloth Gloves 6.x -->
			<item id="114150062" count="1" race="ASMODIANS" /> <!-- Old Cloth Shoes 6.x -->
			<item id="102050064" count="1" race="ELYOS" /> <!-- Old Stringed Instrument 6.x -->
			<item id="102220102" count="1" race="ELYOS" /> <!-- Old Paint Rings 7.x -->
			<item id="110150061" count="1" race="ELYOS" /> <!-- Old Tunic 6.x -->
			<item id="113150061" count="1" race="ELYOS" /> <!-- Old Cloth Breeches 6.x -->
			<item id="111150061" count="1" race="ELYOS" /> <!-- Old Cloth Gloves 6.x -->
			<item id="114150061" count="1" race="ELYOS" /> <!-- Old Cloth Shoes 6.x -->
			<item id="160020008" count="10" race="PC_ALL" /> <!-- Malodor Juice 6.x -->
			<item id="169300002" count="20" race="PC_ALL" /> <!-- Bandage 6.x -->
			<item id="162005039" count="50" race="PC_ALL" /> <!-- Apprentices Recovery Potion 6.x -->
			<item id="162005040" count="50" race="PC_ALL" /> <!-- Apprentices Recovery Serum 6.x -->
		</items>
	</player_data>
</player_initial_data>
