=== vilinian/Mobius_AionEmu/dist/game/data/static_data/items/item_skill_enhances.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../modifiers.xsd" />
	<xs:element name="item_skill_enhances">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item_skill_enhance" type="SkillEnhanceTemplate" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="SkillEnhanceTemplate">
		<xs:attribute name="id" type="xs:int" use="required" />
		<xs:attribute name="skill_id" type="IntListType" use="required" />
	</xs:complexType>
</xs:schema>

=== vilinian/Mobius_AionEmu/dist/game/data/static_data/items/item_skill_enhances.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- parsed by phpTools from Aion Germany Group (Mariella) at 2020-10-29 17:50 -->
<item_skill_enhances xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="item_skill_enhances.xsd">
	<item_skill_enhance id="1" skill_id="784 826 830" />
	<item_skill_enhance id="2" skill_id="784" />
	<item_skill_enhance id="3" skill_id="1282" />
	<item_skill_enhance id="4" skill_id="1282" />
	<item_skill_enhance id="5" skill_id="1282" />
	<item_skill_enhance id="6" skill_id="725" />
	<item_skill_enhance id="7" skill_id="555" />
	<item_skill_enhance id="8" skill_id="621" />
	<item_skill_enhance id="9" skill_id="554" />
	<item_skill_enhance id="10" skill_id="545" />
	<item_skill_enhance id="11" skill_id="3140" />
	<item_skill_enhance id="12" skill_id="3106" />
	<item_skill_enhance id="13" skill_id="2967" />
	<item_skill_enhance id="14" skill_id="3162" />
	<item_skill_enhance id="15" skill_id="3069" />
	<item_skill_enhance id="16" skill_id="3356" />
	<item_skill_enhance id="17" skill_id="3404" />
	<item_skill_enhance id="18" skill_id="3455" />
	<item_skill_enhance id="19" skill_id="3182" />
	<item_skill_enhance id="20" skill_id="3406" />
	<item_skill_enhance id="21" skill_id="1022" />
	<item_skill_enhance id="22" skill_id="1022" />
	<item_skill_enhance id="23" skill_id="1054" />
	<item_skill_enhance id="24" skill_id="1090" />
	<item_skill_enhance id="25" skill_id="1054" />
	<item_skill_enhance id="26" skill_id="3912" />
	<item_skill_enhance id="27" skill_id="4098" />
	<item_skill_enhance id="28" skill_id="4213" />
	<item_skill_enhance id="29" skill_id="3912" />
	<item_skill_enhance id="30" skill_id="3918" />
	<item_skill_enhance id="31" skill_id="1562" />
	<item_skill_enhance id="32" skill_id="1601" />
	<item_skill_enhance id="33" skill_id="1715" />
	<item_skill_enhance id="34" skill_id="1614" />
	<item_skill_enhance id="35" skill_id="1798" />
	<item_skill_enhance id="36" skill_id="1506" />
	<item_skill_enhance id="37" skill_id="1506" />
	<item_skill_enhance id="38" skill_id="1506" />
	<item_skill_enhance id="39" skill_id="1155" />
	<item_skill_enhance id="40" skill_id="1543" />
	<item_skill_enhance id="41" skill_id="1403" />
	<item_skill_enhance id="42" skill_id="3835" />
	<item_skill_enhance id="43" skill_id="3630" />
	<item_skill_enhance id="44" skill_id="3839" />
	<item_skill_enhance id="45" skill_id="3838" />
	<item_skill_enhance id="46" skill_id="1995" />
	<item_skill_enhance id="47" skill_id="2350" />
	<item_skill_enhance id="48" skill_id="2350" />
	<item_skill_enhance id="49" skill_id="2204" />
	<item_skill_enhance id="50" skill_id="2155" />
	<item_skill_enhance id="51" skill_id="4400" />
	<item_skill_enhance id="52" skill_id="4368" />
	<item_skill_enhance id="53" skill_id="4392" />
	<item_skill_enhance id="54" skill_id="4392" />
	<item_skill_enhance id="55" skill_id="4297" />
	<item_skill_enhance id="56" skill_id="2568" />
	<item_skill_enhance id="57" skill_id="2756" />
	<item_skill_enhance id="58" skill_id="2142" />
	<item_skill_enhance id="59" skill_id="2717" />
	<item_skill_enhance id="60" skill_id="2726" />
	<item_skill_enhance id="61" skill_id="3140 3084 2864 2877 3055 3113 3113" />
	<item_skill_enhance id="62" skill_id="3140 3084 2864 2877 3055 3113 3113" />
	<item_skill_enhance id="63" skill_id="1768 1769 1700 1580 1858 1614 4685" />
	<item_skill_enhance id="64" skill_id="3223 3365 3427 3435 3182 3182 3417 1102 826 950 1010 1066 1118 1075" />
	<item_skill_enhance id="65" skill_id="1403 1259 1526 1250 1385 1533 1155 3740 3740 4668 4668 1447 3742 3834 4408 4264 4253 4300 4221 4234 4234" />
	<item_skill_enhance id="66" skill_id="3223 3365 3427 3435 3182 3182 3417" />
	<item_skill_enhance id="67" skill_id="3223 3365 3427 3435 3182 3182 3417 4670 720 2864 707 2877 710 3140 3084 2864 2877 3055 3113 3113" />
	<item_skill_enhance id="68" skill_id="1614 4083 4073 4073 3977 3977 4176" />
	<item_skill_enhance id="69" skill_id="3140 2864 2877 3055 3113" />
	<item_skill_enhance id="70" skill_id="670 4670 720 2864 707 2877 710" />
	<item_skill_enhance id="71" skill_id="1768 1769 1700 1580 1858 1614 4685" />
	<item_skill_enhance id="72" skill_id="1102 826 950 1010 1066 1118 1075" />
	<item_skill_enhance id="73" skill_id="1403 1259 1526 1250 1385 1533 1155 3740 3740 4668 4668 1447 3742 3834" />
	<item_skill_enhance id="74" skill_id="1403 1259 1526 1250 1385 1533 1155 3740 3740 4668 4668 1447 3742 3834" />
	<item_skill_enhance id="75" skill_id="4408 4264 4253 4300 4221 4234 4234" />
	<item_skill_enhance id="76" skill_id="2125 1957 1911 2219" />
	<item_skill_enhance id="77" skill_id="2322 2210 1942" />
	<item_skill_enhance id="78" skill_id="2819 2779 2741 2833 2426 2498 2415" />
	<item_skill_enhance id="79" skill_id="601 3116 3271 3223 1639" />
	<item_skill_enhance id="80" skill_id="2890 2890 3478 1667 1667 644 3131 3196 1022 1703" />
	<item_skill_enhance id="81" skill_id="769 3066 3340 707 707 707 2877 3182 1102 1858" />
	<item_skill_enhance id="82" skill_id="635 4672 3470 830 1602" />
	<item_skill_enhance id="83" skill_id="4037 1217 2349 2349 2606 2606" />
	<item_skill_enhance id="84" skill_id="4170 1387 3640 2210 4336 2807 1838 3776 3776 1942 4246 2543" />
	<item_skill_enhance id="85" skill_id="4213 1258 3835 2107 4522 2806 4073 1259 3740 1957 4408 2741" />
	<item_skill_enhance id="86" skill_id="3951 3582 3582 2008 4471 2566" />
	<item_skill_enhance id="87" skill_id="1614 4083 4073 4073 3977 3977 4176" />
	<item_skill_enhance id="88" skill_id="670 4670 720 2864 707 2877 710" />
	<item_skill_enhance id="89" skill_id="1614 4083 4073 4073 3977 3977 4176" />
	<item_skill_enhance id="90" skill_id="1614 4083 4073 4073 3977 3977 4176 2819 2779 2741 2833 2426 2498 2415" />
	<item_skill_enhance id="91" skill_id="2350 2125 2219 1957 2142 1911 2132" />
	<item_skill_enhance id="92" skill_id="601 2890 644 769 635 3116 2890 3131 3066 4672 3271 3478 3196 3340 3470 3223 1667 1022 707 830 1639 1667 1703 707 1602" />
	<item_skill_enhance id="93" skill_id="4037 4170 1838 4213 3951 1217 1387 3776 1258 3582 2349 2107 2142 2008 2132 2606 4336 4246 4522 4471 2606 2807 2543 2806 2566 2349 3640 3776 3835 3582" />
	<item_skill_enhance id="94" skill_id="601 2890 644 769 635 3116 2890 3131 3066 4672 3271 3478 3196 3340 3470 3223 1667 1022 707 830 1639 1667 1703 707 1602 4037 4170 1838 4213 3951 1217 1387 3776 1258 3582 2349 2107 2142 2008 2132 2606 4336 4246 4522 4471 2606 2807 2543 2806 2566 2349 3640 3776 3835 3582" />
	<item_skill_enhance id="95" skill_id="601 2890 644 769 635 3116 2890 3131 3066 4672 3271 3478 3196 3340 3470 3223 1667 1022 707 830 1639 1667 1703 707 1602" />
	<item_skill_enhance id="96" skill_id="4037 4170 1838 4213 3951 1217 1387 3776 1258 3582 2349 2107 2142 2008 2132 2606 4336 4246 4522 4471 2606 2807 2543 2806 2566 2349 3640 3776 3835 3582" />
	<item_skill_enhance id="97" skill_id="601 2890 644 769 635 3116 2890 3131 3066 4672 3271 3478 3196 3340 3470 3223 1667 1022 707 830 1639 1667 1703 707 1602 4037 4170 1838 4213 3951 1217 1387 3776 1258 3582 2349 2107 2142 2008 2132 2606 4336 4246 4522 4471 2606 2807 2543 2806 2566 2349 3640 3776 3835 3582" />
	<item_skill_enhance id="98" skill_id="601 2890 644 769 635 3116 2890 3131 3066 4672 3271 3478 3196 3340 3470 3223 1667 1022 707 830 1639 1667 1703 707 1602" />
	<item_skill_enhance id="99" skill_id="4037 4170 1838 4213 3951 1217 1387 3776 1258 3582 2349 2107 2142 2008 2132 2606 4336 4246 4522 4471 2606 2807 2543 2806 2566 2349 3640 3776 3835 3582" />
	<item_skill_enhance id="100" skill_id="601 2890 644 769 635 3116 2890 3131 3066 4672 3271 3478 3196 3340 3470 3223 1667 1022 707 830 1639 1667 1703 707 1602 4037 4170 1838 4213 3951 1217 1387 3776 1258 3582 2349 2107 2142 2008 2132 2606 4336 4246 4522 4471 2606 2807 2543 2806 2566 2349 3640 3776 3835 3582" />
	<item_skill_enhance id="101" skill_id="601 2890 644 769 635 3116 2890 3131 3066 4672 3271 3478 3196 3340 3470 3223 1667 1022 707 830 1639 1667 1703 707 1602" />
	<item_skill_enhance id="102" skill_id="4037 4170 1838 4213 3951 1217 1387 3776 1258 3582 2349 2107 2142 2008 2132 2606 4336 4246 4522 4471 2606 2807 2543 2806 2566 2349 3640 3776 3835 3582" />
	<item_skill_enhance id="103" skill_id="601 2890 644 769 635 3116 2890 3131 3066 4672 3271 3478 3196 3340 3470 3223 1667 1022 707 830 1639 1667 1703 707 1602 4037 4170 1838 4213 3951 1217 1387 3776 1258 3582 2349 2107 2142 2008 2132 2606 4336 4246 4522 4471 2606 2807 2543 2806 2566 2349 3640 3776 3835 3582" />
	<item_skill_enhance id="104" skill_id="601 2890 644 769 635 3116 2890 3131 3066 4672" />
	<item_skill_enhance id="105" skill_id="1639 1667 1703 707 1602 4037 4170 1838 4213 3951 2606 2807 2543 2806 2566" />
	<item_skill_enhance id="106" skill_id="3271 3478 3196 3340 3470 3223 1667 1022 707 830 2349 2107 2142 2008 2132" />
	<item_skill_enhance id="107" skill_id="1217 1387 3776 1258 3582 2606 4336 4246 4522 4471 2349 3640 3776 3835 3582" />
	<item_skill_enhance id="108" skill_id="663 624 572 604 590 519 531 3072 3038 3038 3085 3125 3094 3071 3385 3482 3283 3415 3500 3306 830 830 1022 1022 950 3182 1054 1066 1637 1614 1814 1838 1838 1627 1875" />
	<item_skill_enhance id="109" skill_id="1814 4150 4054 4098 4098 4128 4054 1226 1385 1385 1167 1391 1391 1184 2171 1912 2186 2055 2180 2322 2256 4281 4425 4403 4273 4431 4567 4339 2399 2399 2399 2763 2426 2807 2530 3790 3838 1403 3630 3839 3835 1155" />
	<item_skill_enhance id="110" skill_id="663 624 572 604 590 519 531 3072 3038 3038 3085 3125 3094 3071 3385 3482 3283 3415 3500 3306 830 830 1022 1022 950 3182 1054 1066 1637 1614 1814 1838 1838 1627 1875" />
	<item_skill_enhance id="111" skill_id="1814 4150 4054 4098 4098 4128 4054 1226 1385 1385 1167 1391 1391 1184 2171 1912 2186 2055 2180 2322 2256 4281 4425 4403 4273 4431 4567 4339 2399 2399 2399 2763 2426 2807 2530 3790 3838 1403 3630 3839 3835 1155" />
