=== vilinian/Mobius_AionEmu/dist/game/data/static_data/items/item_multi_returns.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="item_multi_returns">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" type="ScrollInfo" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ScrollInfo">
		<xs:sequence>
			<xs:element name="loc" type="LocationData" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required" />
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="LocationData">
		<xs:attribute name="worldid" type="xs:int" use="required" />
		<xs:attribute name="desc" type="xs:string" use="required" />
	</xs:complexType>
</xs:schema>

=== vilinian/Mobius_AionEmu/dist/game/data/static_data/items/item_multi_returns.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- parsed by phpTools from Aion Germany Group (Mariella) at 2020-10-29 17:50 -->
<item_multi_returns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="item_multi_returns.xsd">
	<item id="1" name="test_multi_retrun_1">
		<loc worldid="110010000" desc="Sanctum" />
		<loc worldid="210030000" desc="Verteron" />
		<loc worldid="210020000" desc="Eltnen" />
		<loc worldid="210040000" desc="Heiron" />
		<loc worldid="210060000" desc="Theobomos" />
	</item>
	<item id="2" name="test_multi_retrun_2">
		<loc worldid="400010000" desc="Reshanta" />
		<loc worldid="210050000" desc="Inggison" />
		<loc worldid="600020000" desc="Kamar" /> <!-- ??? LF4A - WorldId not defined in client / not active ??? -->
		<loc worldid="600050000" desc="Kaisinel's Beacon" /> <!-- ??? LF5A_L - WorldId not defined in client / not active ??? -->
		<loc worldid="600060000" desc="Pandarunerk's Delve" /> <!-- ??? LDF5B - WorldId not defined in client / not active ??? -->
		<loc worldid="600070000" desc="Segarunerk's Bazaar" /> <!-- ??? LDF5B_UNDER - WorldId not defined in client / not active ??? -->
		<loc worldid="110010000" desc="Sanctum" />
		<loc worldid="210030000" desc="Verteron" />
		<loc worldid="210020000" desc="Eltnen" />
		<loc worldid="210040000" desc="Heiron" />
		<loc worldid="210060000" desc="Theobomos" />
	</item>
	<item id="3" name="test_multi_retrun_3">
		<loc worldid="110010000" desc="Sanctum" />
		<loc worldid="210030000" desc="Verteron" />
		<loc worldid="210020000" desc="Eltnen" />
		<loc worldid="210040000" desc="Heiron" />
		<loc worldid="210060000" desc="Theobomos" />
		<loc worldid="120010000" desc="Pandaemonium" />
		<loc worldid="220030000" desc="Altgard" />
		<loc worldid="220020000" desc="Morheim" />
		<loc worldid="220040000" desc="Beluslan" />
		<loc worldid="220050000" desc="Brusthonin" />
	</item>
	<item id="4" name="test_multi_retrun_4">
		<loc worldid="110010000" desc="Sanctum" />
	</item>
	<item id="5" name="test_multi_retrun_5">
		<loc worldid="110010000" desc="Sanctum" />
		<loc worldid="210030000" desc="Verteron" />
		<loc worldid="210020000" desc="Eltnen" />
		<loc worldid="210040000" desc="Heiron" />
		<loc worldid="210060000" desc="Theobomos" />
		<loc worldid="120010000" desc="Pandaemonium" />
		<loc worldid="220030000" desc="Altgard" />
		<loc worldid="220020000" desc="Morheim" />
		<loc worldid="220040000" desc="Beluslan" />
		<loc worldid="220050000" desc="Brusthonin" />
		<loc worldid="400010000" desc="Reshanta" />
		<loc worldid="210050000" desc="Inggison" />
		<loc worldid="600020000" desc="Kamar" /> <!-- ??? LF4A - WorldId not defined in client / not active ??? -->
		<loc worldid="600050000" desc="Kaisinel's Beacon" /> <!-- ??? LF5A_L - WorldId not defined in client / not active ??? -->
		<loc worldid="600060000" desc="Pandarunerk's Delve" /> <!-- ??? LDF5B - WorldId not defined in client / not active ??? -->
		<loc worldid="600070000" desc="Segarunerk's Bazaar" /> <!-- ??? LDF5B_UNDER - WorldId not defined in client / not active ??? -->
		<loc worldid="600070000" desc="Segarunerk's Bazaar" /> <!-- ??? LDF5B_UNDER_2 - WorldId not defined in client / not active ??? -->
		<loc worldid="600060000" desc="Pandarunerk" /> <!-- ??? LDF5B_2 - WorldId not defined in client / not active ??? -->
		<loc worldid="600050000" desc="Danuar Spire" /> <!-- ??? LDF5A_D - WorldId not defined in client / not active ??? -->
		<loc worldid="700010000" desc="Oriel" />
	</item>
	<item id="6" name="lf_multi_retrun_1">
		<loc worldid="110010000" desc="Sanctum" />
		<loc worldid="210040000" desc="Heiron" />
		<loc worldid="110070000" desc="Kaisinel_academy" />
		<loc worldid="700010000" desc="Oriel" />
		<loc worldid="210050000" desc="Inggison" />
	</item>
	<item id="7" name="df_multi_retrun_1">
		<loc worldid="120010000" desc="Pandaemonium" />
		<loc worldid="220040000" desc="Beluslan" />
		<loc worldid="120080000" desc="Marchutan_priory" />
		<loc worldid="710010000" desc="Pernon" />
		<loc worldid="220070000" desc="Gelkmaros" />
	</item>
	<item id="8" name="lf_multi_retrun_sp">
		<loc worldid="110010000" desc="Sanctum" />
		<loc worldid="210030000" desc="Verteron" />
		<loc worldid="210020000" desc="Eltnen" />
		<loc worldid="210040000" desc="Heiron" />
		<loc worldid="210060000" desc="Theobomos" />
		<loc worldid="400010000" desc="Reshanta" />
	</item>
	<item id="9" name="df_multi_retrun_sp">
		<loc worldid="120010000" desc="Pandaemonium" />
		<loc worldid="220030000" desc="Altgard" />
		<loc worldid="220020000" desc="Morheim" />
		<loc worldid="220040000" desc="Beluslan" />
		<loc worldid="220050000" desc="Brusthonin" />
		<loc worldid="400010000" desc="Reshanta" />
	</item>
	<item id="10" name="ldf7_multi_return_L">
		<loc worldid="800050000" desc="Lakrum" />
		<loc worldid="800050000" desc="Lakrum" />
		<loc worldid="800050000" desc="Lakrum" />
		<loc worldid="800050000" desc="Lakrum" />
		<loc worldid="800050000" desc="Lakrum" />
		<loc worldid="800050000" desc="Lakrum" />
	</item>
	<item id="11" name="ldf7_multi_return_D">
		<loc worldid="800050000" desc="Lakrum" />
		<loc worldid="800050000" desc="Lakrum" />
		<loc worldid="800050000" desc="Lakrum" />
		<loc worldid="800050000" desc="Lakrum" />
		<loc worldid="800050000" desc="Lakrum" />
		<loc worldid="800050000" desc="Lakrum" />
	</item>
	<item id="12" name="lugbug_lf_multi_retrun_75a">
		<loc worldid="110010000" desc="Sanctum" />
		<loc worldid="210040000" desc="Heiron" />
		<loc worldid="110070000" desc="Kaisinel_academy" />
		<loc worldid="700010000" desc="Oriel" />
		<loc worldid="210050000" desc="Inggison" />
	</item>
	<item id="13" name="lugbug_df_multi_retrun_75a">
		<loc worldid="120010000" desc="Pandaemonium" />
		<loc worldid="220040000" desc="Beluslan" />
		<loc worldid="120080000" desc="Marchutan_priory" />
		<loc worldid="710010000" desc="Pernon" />
		<loc worldid="220070000" desc="Gelkmaros" />
	</item>
	<item id="14" name="ldf8_multi_return_L">
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
	</item>
	<item id="15" name="ldf8_multi_return_D">
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
		<loc worldid="800060000" desc="Dumaha" />
	</item>
	<item id="16" name="ldf5_multi_return_L">
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
	</item>
	<item id="17" name="ldf5_multi_return_D">
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
	</item>
	<item id="18" name="ldf5_multi_return_L_01">
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
	</item>
	<item id="19" name="ldf5_multi_return_D_01">
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
		<loc worldid="800030000" desc="Red_katalam_north" />
	</item>
</item_multi_returns>
