=== vilinian/Mobius_AionEmu/dist/game/data/static_data/locations/rift/rift_locations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
           jxb:version="2.1">
	<xs:include schemaLocation="../../global_types.xsd" />
	<xs:element name="rift_locations">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="rift_location" type="Rift" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Rift">
		<xs:attribute name="id" type="xs:int" use="required" />
		<xs:attribute name="world" type="xs:int" />
	</xs:complexType>
</xs:schema>

=== vilinian/Mobius_AionEmu/dist/game/data/static_data/locations/rift/rift_locations.xml
<?xml version="1.0" encoding="UTF-8"?>
<rift_locations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rift_locations.xsd">
	<rift_location id="2140" world="210040000" />
	<rift_location id="2141" world="210040000" />
	<rift_location id="2142" world="210040000" />
	<rift_location id="2143" world="210040000" />
	<rift_location id="2144" world="210040000" />
	<rift_location id="2145" world="210040000" />
	<rift_location id="2146" world="210040000" />
	<rift_location id="2150" world="210050000" />
	<rift_location id="2151" world="210050000" />
	<rift_location id="2152" world="210050000" />
	<rift_location id="2153" world="210050000" />
	<rift_location id="2170" world="210070000" /> <!-- Cygnea -->
	<rift_location id="2171" world="210070000" /> <!-- Cygnea -->
	<rift_location id="2172" world="210070000" /> <!-- Cygnea -->
	<rift_location id="2173" world="210070000" /> <!-- Cygnea -->
	<rift_location id="2174" world="210070000" /> <!-- Cygnea -->
	<rift_location id="2175" world="210070000" /> <!-- Cygnea -->
	<rift_location id="2176" world="210070000" /> <!-- Cygnea -->
	<rift_location id="2177" world="210070000" /> <!-- Cygnea -->
	<rift_location id="2178" world="210070000" /> <!-- Cygnea -->
	<rift_location id="2240" world="220040000" />
	<rift_location id="2241" world="220040000" />
	<rift_location id="2242" world="220040000" />
	<rift_location id="2243" world="220040000" />
	<rift_location id="2244" world="220040000" />
	<rift_location id="2245" world="220040000" />
	<rift_location id="2246" world="220040000" />
	<rift_location id="2270" world="220070000" />
	<rift_location id="2271" world="220070000" />
	<rift_location id="2272" world="220070000" />
	<rift_location id="2273" world="220070000" />
	<rift_location id="2280" world="220080000" /> <!-- Enshar -->
	<rift_location id="2281" world="220080000" /> <!-- Enshar -->
	<rift_location id="2282" world="220080000" /> <!-- Enshar -->
	<rift_location id="2283" world="220080000" /> <!-- Enshar -->
	<rift_location id="2284" world="220080000" /> <!-- Enshar -->
	<rift_location id="2285" world="220080000" /> <!-- Enshar -->
	<rift_location id="2286" world="220080000" /> <!-- Enshar -->
	<rift_location id="2287" world="220080000" /> <!-- Enshar -->
	<rift_location id="2288" world="220080000" /> <!-- Enshar -->
</rift_locations>
