=== vilinian/Mobius_AionEmu/dist/game/data/static_data/service_bonusattr/players_bonus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.1">
	<xs:include schemaLocation="../modifiers.xsd" />
	<xs:element name="players_service_bonusattrs">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="players_service_bonusattr" type="PlayersBonusServiceAttr" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="PlayersBonusServiceAttr">
		<xs:sequence>
			<xs:element name="apply_bonus" type="PlayersBonusPenaltyAttr" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="buff_id" type="xs:int" use="required" />
	</xs:complexType>
	<xs:complexType name="PlayersBonusPenaltyAttr">
		<xs:attribute name="stat" type="modifiersenum" use="required" />
		<xs:attribute name="func" type="StatFunc" use="required" />
		<xs:attribute name="value" type="xs:int" use="required" />
	</xs:complexType>
</xs:schema>

=== vilinian/Mobius_AionEmu/dist/game/data/static_data/service_bonusattr/players_bonus.xml
<?xml version="1.0" encoding="UTF-8"?>
<players_service_bonusattrs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="players_bonus.xsd">
	<players_service_bonusattr buff_id="1" />
	<!-- Ascension Boost -->
	<players_service_bonusattr buff_id="2">
		<apply_bonus stat="DR_BOOST" func="ADD" value="10" />
	</players_service_bonusattr>
	<!-- Veteran Boost -->
	<players_service_bonusattr buff_id="3">
		<apply_bonus stat="DR_BOOST" func="ADD" value="10" />
	</players_service_bonusattr>
	<!-- Account Game Experience Item "DIAMOND_01 Green" -->
	<players_service_bonusattr buff_id="4" />
	<!-- Account Game Experience Item "DIAMOND_01 Blue" -->
	<players_service_bonusattr buff_id="5" />
	<!-- Account Game Experience Item "DIAMOND_01 Pink" -->
	<players_service_bonusattr buff_id="6" />
	<!-- Account Game Experience Item "DIAMOND_01 Yellow" -->
	<players_service_bonusattr buff_id="7" />
	<!-- Account Game Experience Item "DIAMOND_01 Orange" -->
	<players_service_bonusattr buff_id="8" />
	<!-- Account Game Experience Item "DIAMOND_01 Red" -->
	<players_service_bonusattr buff_id="9" />
	<!-- Eminence Of The Bearer -->
	<players_service_bonusattr buff_id="10">
		<apply_bonus stat="DR_BOOST" func="ADD" value="10" />
		<apply_bonus stat="SPEED" func="PERCENT" value="5" />
	</players_service_bonusattr>
</players_service_bonusattrs>
