=== vilinian/Mobius_AionEmu/dist/game/data/packets/packets.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="packets">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="packetType" name="packet" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
			<xs:attribute type="xs:long" name="delay" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:complexType name="packetType">
		<xs:sequence>
			<xs:element type="partType" name="part" maxOccurs="unbounded" minOccurs="1" />
		</xs:sequence>
		<xs:attribute type="xs:string" name="opcode" use="required" />
		<xs:attribute type="xs:long" name="delay" use="optional" />
	</xs:complexType>
	<xs:complexType name="partType">
		<xs:attribute type="partTypes" name="type" use="required" />
		<xs:attribute type="xs:string" name="value" use="required" />
		<xs:attribute type="xs:int" name="repeat" use="optional" />
	</xs:complexType>
	<xs:simpleType name="partTypes">
		<xs:restriction base="xs:string">
			<xs:enumeration value="d" />
			<xs:enumeration value="h" />
			<xs:enumeration value="c" />
			<xs:enumeration value="f" />
			<xs:enumeration value="e" />
			<xs:enumeration value="q" />
			<xs:enumeration value="s" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== vilinian/Mobius_AionEmu/dist/game/data/packets/demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<packets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="packets.xsd" delay="2000">
	<!--
    Information:
            * To send this mapping use admin command '//send demo'.
            * Each packet is sent with delay {packets#delay} between them.
            * Each packet part can be repeated many times by specifying attribute {part#repeat}
                    i.e. <part type="c" value="0x00" repeat="29" />
    -->
	<!-- Example: send first SM_MESSAGE packet -->
	<!-- Format: ccdhS -->
	<packet opcode="0x1B">
		<part type="c" value="0x19" />
		<!-- chat type: ANNOUNCEMENTS -->
		<part type="c" value="0x00" />
		<part type="d" value="${objectId}" />
		<!-- write sender objectId -->
		<part type="h" value="0x00" />
		<part type="s" value="Hello, World!" />
	</packet>
	<!--
    Example: send second SM_MESSAGE packet.
    Packet will be sent after {packets#delay} milliseconds.
    -->
	<packet opcode="0x1B">
		<part type="c" value="0x19" />
		<part type="c" value="0x00" />
		<part type="d" value="${objectId}" />
		<part type="h" value="0x00" />
		<part type="s" value="New message!" />
	</packet>
</packets>
