=== vilinian/Mobius_AionEmu/dist/game/data/static_data/events_config/atreian_passports.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="atreian_passports">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="atreian_passport" type="AtreianPassport" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="AtreianPassport">
		<xs:sequence>
			<xs:element name="rewards" type="AtreianPassportRewards" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="active" type="xs:int" use="required" />
		<xs:attribute name="attend_type" type="AttendType" use="required" />
	</xs:complexType>

	<xs:complexType name="AtreianPassportRewards">
		<xs:attribute name="reward_item_num" type="xs:int" use="required" />
		<xs:attribute name="reward_item_count" type="xs:int" />
		<xs:attribute name="reward_item" type="xs:int" use="required" />
		<xs:attribute name="name" type="xs:string" />
	</xs:complexType>

	<xs:simpleType name="AttendType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PC_BASIC" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== vilinian/Mobius_AionEmu/dist/game/data/static_data/events_config/atreian_passports.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- parsed by phpTools from Aion Germany Group (Mariella) at 2020-07-22 20:03 -->
<atreian_passports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="atreian_passports.xsd">
	<atreian_passport id="10" name="2017_attend_01_PCbasic" active="0" attend_type="PC_BASIC">
		<rewards reward_item_num="1" reward_item_count="1" reward_item="188071582" name="[Internet café] Bundle of Consumables" />
		<rewards reward_item_num="2" reward_item_count="1" reward_item="169627008" name="Internet Café Cookie - Special Attribute Buff" />
		<rewards reward_item_num="3" reward_item_count="1" reward_item="169627003" name="Internet Café Cookie - Special Boost Buff" />
		<rewards reward_item_num="4" reward_item_count="30" reward_item="190099000" name="Transformation Scroll" />
		<rewards reward_item_num="5" reward_item_count="1" reward_item="162005050" name="[Event] Lodas' Large Silver Star" />
		<rewards reward_item_num="6" reward_item_count="1" reward_item="166023112" name="[Event] Legendary PvE Enchantment Stone (7 days)" />
		<rewards reward_item_num="7" reward_item_count="1" reward_item="166033113" name="[Event] Legendary PvP Enchantment Stone (7 days)" />
	</atreian_passport>
	<atreian_passport id="11" name="Bmpack_attend_01_PCbasic" active="1" attend_type="PC_BASIC">
		<rewards reward_item_num="1" reward_item_count="220" reward_item="186000509" name="Shugo Gold" />
		<rewards reward_item_num="2" reward_item_count="1" reward_item="188055484" name="Little Luna Bundle" />
		<rewards reward_item_num="3" reward_item_count="25" reward_item="188120097" name="Polishing Powder" />
		<rewards reward_item_num="4" reward_item_count="1" reward_item="188120049" name="[Event] Legendary Daevanion Skill Chest Fragment" />
		<rewards reward_item_num="5" reward_item_count="1" reward_item="188070176" name="Gold Ingots Bundle" />
		<rewards reward_item_num="6" reward_item_count="1" reward_item="188073757" name="Box of Odian Fragments" />
		<rewards reward_item_num="7" reward_item_count="1" reward_item="190095105" name="[Event] Special Transformation Contract (62 types)" />
	</atreian_passport>
</atreian_passports>
