=== vilinian/Mobius_AionEmu/dist/game/config/ingameshop/in_game_shop.xsd
<?xml version="1.0" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.1">

	<xs:element name="in_game_shop">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="category" type="IGCategory" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="IGCategory">
		<xs:sequence>
			<xs:element name="sub_category" type="IGSubCategory" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required" />
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="IGSubCategory">
		<xs:attribute name="id" type="xs:int" use="required" />
		<xs:attribute name="name" type="xs:string" use="required" />
	</xs:complexType>
</xs:schema>

=== vilinian/Mobius_AionEmu/dist/game/config/ingameshop/in_game_shop.xml
<?xml version="1.0" encoding="UTF-8"?>
<in_game_shop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="in_game_shop.xsd">

	<!-- Supporting Items -->
	<category id="0" name="Support">
		<sub_category id="10" name="Boost" />
		<sub_category id="11" name="Potions I" />
		<sub_category id="12" name="Potions II" />
		<sub_category id="13" name="Potions III" />
		<sub_category id="14" name="Potions IV" />
		<sub_category id="15" name="Scrolls I" />
		<sub_category id="16" name="Scrolls II" />
		<sub_category id="17" name="Scrolls III" />
		<sub_category id="18" name="Drinks/Jelly" />
		<sub_category id="19" name="Food I" />
		<sub_category id="20" name="Food II" />
		<sub_category id="21" name="Food III" />
		<sub_category id="22" name="Food IV" />
		<sub_category id="23" name="Candy" />
		<sub_category id="24" name="General Goods I" />
		<sub_category id="25" name="General Goods II" />
		<sub_category id="26" name="Time Scrolls" />
	</category>

	<!-- Menu 2 -->
	<category id="1" name="Enchant">
		<sub_category id="27" name="Manastone I" />
		<sub_category id="28" name="Manastone II" />
		<sub_category id="29" name="Manastone III" />
		<sub_category id="30" name="Manastone IV" />
		<sub_category id="31" name="Manastone V" />
		<sub_category id="32" name="Manastone VI" />
		<sub_category id="33" name="Manastone VII" />
		<sub_category id="34" name="Godstones" />
		<sub_category id="35" name="Idian I" />
		<sub_category id="36" name="Idian II" />
		<sub_category id="37" name="Idian III" />
		<sub_category id="38" name="Idian IV" />
		<sub_category id="39" name="Enchantment Stones" />
		<sub_category id="40" name="Supplements" />
		<sub_category id="41" name="Conditioning" />
		<sub_category id="42" name="Extraction" />
		<sub_category id="43" name="Tuning" />
	</category>

	<!-- Menu 3 -->
	<category id="2" name="Supply">
		<sub_category id="44" name="Aether" />
		<sub_category id="45" name="Ore: Metal" />
		<sub_category id="46" name="Ore: Gemstones" />
		<sub_category id="47" name="Wooden Logs" />
		<sub_category id="48" name="Cloth Fiber" />
		<sub_category id="49" name="Herbs" />
		<sub_category id="50" name="Vegetables" />
		<sub_category id="51" name="Fish" />
		<sub_category id="52" name="Shellfish" />
		<sub_category id="53" name="Fruit" />
		<sub_category id="54" name="Meat/Essence" />
		<sub_category id="55" name="Elemental Stones" />
		<sub_category id="56" name="Hides" />
		<sub_category id="57" name="Flux" />
		<sub_category id="58" name="Material Drops" />
		<sub_category id="59" name="Morph Catalyst" />
		<sub_category id="60" name="Essencetapper" />
	</category>

	<!-- Menu 4 -->
	<category id="3" name="Character">
		<sub_category id="61" name="Name Change" />
		<sub_category id="62" name="Plastic Surgery" />
		<sub_category id="63" name="Cube/Warehouse" />
		<sub_category id="64" name="Title Cards" />
		<sub_category id="65" name="Emotion Cards" />
		<sub_category id="66" name="Motion Cards" />
		<sub_category id="67" name="Morph Methods" />
		<sub_category id="68" name="Trade: Coins [E]" />
		<sub_category id="69" name="Trade: Coins [A]" />
		<sub_category id="70" name="Trade: Abyss Points" />
		<sub_category id="71" name="Trade: Siege Warfare" />
		<sub_category id="72" name="Trade: Unsorted" />
		<sub_category id="73" name="Firecrackers" />
		<sub_category id="74" name="" />
		<sub_category id="75" name="" />
		<sub_category id="76" name="" />
		<sub_category id="77" name="" />
	</category>

	<!-- Menu 5 -->
	<category id="4" name="Mounts/Pets">
		<sub_category id="78" name="Mounts" />
		<sub_category id="79" name="Pets I" />
		<sub_category id="80" name="Pets II" />
		<sub_category id="81" name="Pets III" />
		<sub_category id="82" name="Pets IV" />
		<sub_category id="83" name="Pets V" />
		<sub_category id="84" name="Pets VI" />
		<sub_category id="85" name="Pets VII" />
		<sub_category id="86" name="Pets VIII" />
		<sub_category id="87" name="Sidekicks I" />
		<sub_category id="88" name="Sidekicks II" />
		<sub_category id="89" name="Pet Books" />
		<sub_category id="90" name="Pet Food: Common" />
		<sub_category id="91" name="Pet Food: Rare" />
		<!--	<sub_category id="92" name="" />
                <sub_category id="93" name="" />
                <sub_category id="94" name="" /> -->
	</category>

	<!-- Menu 6 -->
	<category id="5" name="Gear">
		<sub_category id="95" name="Dye" />
		<sub_category id="96" name="Headwear I" />
		<sub_category id="97" name="Headwear II" />
		<sub_category id="98" name="Costume Skins I" />
		<sub_category id="99" name="Costume Skins II" />
		<sub_category id="100" name="Weaponskins I" />
		<sub_category id="101" name="Weaponskins II" />
		<sub_category id="102" name="Armorskins I" />
		<sub_category id="103" name="Armorskins II" />
		<sub_category id="104" name="Wings I" />
		<sub_category id="105" name="Wings II" />
		<sub_category id="106" name="" />
		<sub_category id="107" name="" />
		<sub_category id="108" name="" />
		<sub_category id="109" name="" />
		<sub_category id="110" name="" />
		<sub_category id="111" name="" />
	</category>

	<!-- Menu 7 -->
	<category id="6" name="Housing">
		<sub_category id="112" name="House Remodeling" />
		<sub_category id="113" name="Trade: Housing" />
		<sub_category id="114" name="Paint (Furniture)" />
		<sub_category id="115" name="Hearthbloom" />
		<sub_category id="116" name="Merchants" />
		<sub_category id="117" name="Cabinet/Shelf" />
		<sub_category id="118" name="Bed/Couch" />
		<sub_category id="119" name="Chair/Table" />
		<sub_category id="120" name="Art/Decoration" />
		<sub_category id="121" name="Light/Items" />
		<sub_category id="122" name="Carpet/Screen" />
		<sub_category id="123" name="Wallpapers/etc" />
		<sub_category id="124" name="Souvenir" />
		<sub_category id="125" name="Outdoor" />
		<sub_category id="126" name="Wall/Frame/Roof" />
		<sub_category id="127" name="Lawn/Fence/Door" />
		<!-- END OF SUB_CATEGORY :( -->
		<sub_category id="128" name="" />
		<!-- DO NOT USE, WILL NOT WORK!!! -->
	</category>

	<!-- Menu 8 -->
	<category id="7" name="GM">
		<sub_category id="92" name="GM Items I" />
		<sub_category id="93" name="GM Items II" />
		<sub_category id="94" name="GM Items III" />
	</category>


</in_game_shop>

=== vilinian/Mobius_AionEmu/dist/game/config/ingameshop/default_in_game_shop.xml
<?xml version="1.0" encoding="UTF-8"?>
<in_game_shop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="in_game_shop.xsd">
	<!-- can be more category -->
	<category id="0" name="ELYOS">
		<sub_category id="3" name="Clothing" />
		<sub_category id="4" name="Hats" />
		<sub_category id="5" name="Food" />
		<sub_category id="6" name="Drinks" />
		<sub_category id="7" name="Paint" />
		<sub_category id="8" name="Titles" />
		<sub_category id="9" name="Modifications" />
		<sub_category id="10" name="Modifications of wea" />
		<sub_category id="11" name="Pets" />
		<sub_category id="12" name="Wings" />
		<sub_category id="13" name="Recipes" />
		<sub_category id="14" name="Items collection" />
		<sub_category id="15" name="Miscellaneous" />
		<sub_category id="16" name="Asmodian hairstyles" />
		<sub_category id="17" name="Elyos hairstyles" />
		<sub_category id="18" name="Potions" />
		<sub_category id="19" name="Emotions" />
	</category>
	<category id="1" name="ASMODIANS">
		<sub_category id="3" name="Clothing" />
		<sub_category id="4" name="Hats" />
		<sub_category id="5" name="Food" />
		<sub_category id="6" name="Drinks" />
		<sub_category id="7" name="Paint" />
		<sub_category id="8" name="Titles" />
		<sub_category id="9" name="Modifications" />
		<sub_category id="10" name="Modifications of wea" />
		<sub_category id="11" name="Pets" />
		<sub_category id="12" name="Wings" />
		<sub_category id="13" name="Recipes" />
		<sub_category id="14" name="Items collection" />
		<sub_category id="15" name="Miscellaneous" />
		<sub_category id="16" name="Asmodian hairstyles" />
		<sub_category id="17" name="Elyos hairstyles" />
		<sub_category id="18" name="Potions" />
		<sub_category id="19" name="Emotions" />
	</category>
</in_game_shop>
