=== vilinian/Mobius_AionEmu/dist/game/data/static_data/stats/stats.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../global_types.xsd" />
	<xs:include schemaLocation="../import.xsd" />
	<xs:element name="player_stats_templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="player_stats" type="playerStatsTemplateType" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="summon_stats_templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="summon_stats" type="summonStatsTemplateType" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="playerStatsTemplateType">
		<xs:sequence>
			<xs:element name="stats_template" type="playerStatsTemplate" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="class" type="playerClass" use="required" />
		<xs:attribute name="level" type="xs:byte" use="required" />
	</xs:complexType>
	<xs:complexType name="playerStatsTemplate">
		<xs:complexContent>
			<xs:extension base="statsTemplate">
				<xs:attribute name="power" type="xs:int" use="required" />
				<xs:attribute name="health" type="xs:int" use="required" />
				<xs:attribute name="agility" type="xs:int" use="required" />
				<xs:attribute name="accuracy" type="xs:int" use="required" />
				<xs:attribute name="knowledge" type="xs:int" use="required" />
				<xs:attribute name="will" type="xs:int" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="summonStatsTemplateType">
		<xs:sequence>
			<xs:element name="stats_template" type="summonStatsTemplate" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="npc_id_light" type="xs:int" />
		<xs:attribute name="npc_id_dark" type="xs:int" />
		<xs:attribute name="level" type="xs:byte" use="required" />
	</xs:complexType>
	<xs:complexType name="summonStatsTemplate">
		<xs:complexContent>
			<xs:extension base="statsTemplate">
				<xs:attribute name="pdefense" type="xs:int" use="required" />
				<xs:attribute name="mresist" type="xs:int" use="required" />
				<xs:attribute name="mcrit" type="xs:int" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="statsTemplate" abstract="true">
		<xs:sequence>
			<xs:element name="speeds" type="CreatureSpeeds" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="maxHp" type="xs:int" use="required" />
		<xs:attribute name="maxMp" type="xs:int" />
		<xs:attribute name="evasion" type="xs:int" />
		<xs:attribute name="block" type="xs:int" />
		<xs:attribute name="parry" type="xs:int" />
		<xs:attribute name="main_hand_attack" type="xs:int" />
		<xs:attribute name="main_hand_accuracy" type="xs:int" />
		<xs:attribute name="main_hand_crit_rate" type="xs:int" />
		<xs:attribute name="magic_accuracy" type="xs:int" />
		<xs:attribute name="crit_spell" type="xs:int" />
		<xs:attribute name="strike_resist" type="xs:int" />
		<xs:attribute name="spell_resist" type="xs:int" />
		<xs:attribute name="pvp_attack" type="xs:int" />
		<xs:attribute name="pvp_defense" type="xs:int" />
		<xs:attribute name="pve_attack" type="xs:int" />
		<xs:attribute name="pve_defense" type="xs:int" />
	</xs:complexType>
	<xs:complexType name="CreatureSpeeds">
		<xs:attribute name="walk" type="xs:float" />
		<xs:attribute name="group_walk" type="xs:float" />
		<xs:attribute name="run" type="xs:float" />
		<xs:attribute name="run_fight" type="xs:float" />
		<xs:attribute name="group_run_fight" type="xs:float" />
		<xs:attribute name="fly" type="xs:float" />
	</xs:complexType>
</xs:schema>

=== vilinian/Mobius_AionEmu/dist/game/data/static_data/stats/player/scout-templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<player_stats_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../stats.xsd">
	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="SCOUT" level="1">
		<stats_template maxHp="219" maxMp="170" evasion="105" block="105" parry="105" main_hand_attack="18" main_hand_accuracy="218" main_hand_crit_rate="3" magic_accuracy="14" crit_spell="50" strike_resist="90" spell_resist="50" power="100" health="100" agility="110" accuracy="110" knowledge="90" will="90" pve_attack="0" pve_defense="0" pvp_attack="0" pvp_defense="0">
			<speeds walk="1.5" run="6" fly="9" />
		</stats_template>
	</player_stats>
	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="SCOUT" level="2">
		<stats_template maxHp="261" maxMp="240" evasion="117" block="117" parry="117" main_hand_attack="18" main_hand_accuracy="226" main_hand_crit_rate="3" magic_accuracy="28" crit_spell="50" strike_resist="90" spell_resist="50" power="100" health="100" agility="110" accuracy="110" knowledge="90" will="90" pve_attack="0" pve_defense="0" pvp_attack="0" pvp_defense="0">
			<speeds walk="1.5" run="6" fly="9" />
		</stats_template>
	</player_stats>
	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="SCOUT" level="3">
		<stats_template maxHp="305" maxMp="310" evasion="130" block="130" parry="130" main_hand_attack="18" main_hand_accuracy="234" main_hand_crit_rate="3" magic_accuracy="42" crit_spell="50" strike_resist="90" spell_resist="50" power="100" health="100" agility="110" accuracy="110" knowledge="90" will="90" pve_attack="0" pve_defense="0" pvp_attack="0" pvp_defense="0">
			<speeds walk="1.5" run="6" fly="9" />
		</stats_template>
	</player_stats>
	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="SCOUT" level="4">
		<stats_template maxHp="351" maxMp="380" evasion="142" block="142" parry="142" main_hand_attack="18" main_hand_accuracy="242" main_hand_crit_rate="3" magic_accuracy="57" crit_spell="50" strike_resist="90" spell_resist="50" power="100" health="100" agility="110" accuracy="110" knowledge="90" will="90" pve_attack="0" pve_defense="0" pvp_attack="0" pvp_defense="0">
			<speeds walk="1.5" run="6" fly="9" />
		</stats_template>
	</player_stats>
	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="SCOUT" level="5">
		<stats_template maxHp="399" maxMp="450" evasion="155" block="155" parry="155" main_hand_attack="18" main_hand_accuracy="250" main_hand_crit_rate="3" magic_accuracy="71" crit_spell="50" strike_resist="90" spell_resist="50" power="100" health="100" agility="110" accuracy="110" knowledge="90" will="90" pve_attack="0" pve_defense="0" pvp_attack="0" pvp_defense="0">
			<speeds walk="1.5" run="6" fly="9" />
		</stats_template>
	</player_stats>
	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="SCOUT" level="6">
		<stats_template maxHp="449" maxMp="520" evasion="167" block="167" parry="167" main_hand_attack="18" main_hand_accuracy="258" main_hand_crit_rate="3" magic_accuracy="85" crit_spell="50" strike_resist="90" spell_resist="50" power="100" health="100" agility="110" accuracy="110" knowledge="90" will="90" pve_attack="0" pve_defense="0" pvp_attack="0" pvp_defense="0">
			<speeds walk="1.5" run="6" fly="9" />
		</stats_template>
	</player_stats>
	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="SCOUT" level="7">
		<stats_template maxHp="501" maxMp="590" evasion="179" block="179" parry="179" main_hand_attack="18" main_hand_accuracy="266" main_hand_crit_rate="3" magic_accuracy="99" crit_spell="50" strike_resist="90" spell_resist="50" power="100" health="100" agility="110" accuracy="110" knowledge="90" will="90" pve_attack="0" pve_defense="0" pvp_attack="0" pvp_defense="0">
			<speeds walk="1.5" run="6" fly="9" />
		</stats_template>
	</player_stats>
	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="SCOUT" level="8">
		<stats_template maxHp="555" maxMp="660" evasion="192" block="192" parry="192" main_hand_attack="18" main_hand_accuracy="274" main_hand_crit_rate="3" magic_accuracy="114" crit_spell="50" strike_resist="90" spell_resist="50" power="100" health="100" agility="110" accuracy="110" knowledge="90" will="90" pve_attack="0" pve_defense="0" pvp_attack="0" pvp_defense="0">
			<speeds walk="1.5" run="6" fly="9" />
		</stats_template>
	</player_stats>
	<!-- Checked By Kamui 10/2009 at US Retail -->
	<player_stats class="SCOUT" level="9">
		<stats_template maxHp="612" maxMp="730" evasion="204" block="204" parry="204" main_hand_attack="18" main_hand_accuracy="282" main_hand_crit_rate="3" magic_accuracy="128" crit_spell="50" strike_resist="90" spell_resist="50" power="100" health="100" agility="110" accuracy="110" knowledge="90" will="90" pve_attack="0" pve_defense="0" pvp_attack="0" pvp_defense="0">
			<speeds walk="1.5" run="6" fly="9" />
		</stats_template>
	</player_stats>
</player_stats_templates>
